CREATE DATABASE IF NOT EXISTS `cswowd` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS `mmfpm` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS `dbc_335` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;